server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    #配置关闭自我保护
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
                  # http://localhost:8761/eureka/
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
